"""add event table

Revision ID: 6d3a322fb78d
Revises: 181820ecb1cd
Create Date: 2025-08-21 18:09:17.871528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d3a322fb78d'
down_revision = '181820ecb1cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(length=50), nullable=False),
    sa.Column('event_date', sa.DateTime(), nullable=False),
    sa.Column('organizer_name', sa.String(length=50), nullable=False),
    sa.Column('organizer_contact', sa.String(length=50), nullable=True),
    sa.Column('start_location', sa.String(length=50), nullable=True),
    sa.Column('comments', sa.String(), nullable=True),
    sa.Column('pin', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event')
    # ### end Alembic commands ###
